server:
  port: 8040

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

management:
  security:
    enabled: false

zuul:
  routes:
    bookapi:
      path: /book/**
    userauth:
      path: /auth/**
    userapi:
      path: /user/**
    orderapi:
      path: /order/**
    reapi:
      path: /recommend/**
  ignored-services: '*'
  sensitive-headers:

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 6000

