server:
  port: 9099

eureka:
  client:
    service-url:
      default-zone: http://localhost:9761/eureka
  instance:
    prefer-ip-address: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recom?characterEncoding=utf8&userSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

aliyun:
  oss:
    endpoint: oss-cn-zhangjiakou.aliyuncs.com
    accessKeyId: LTAI0Rg8eHYYP8Sp
    accessKeySecret: GocnuZ3E5eqTymnrL21Ib7aNgrkynF
    bucketName: book-sell
    policy:
      expire: 300
    maxSize: 10
    callback: http://localhost:8080/aliyun/oss/callback
    dir:
      prefix: user/images/
